### ISSUE TITLE
Sir what is the password of tool..?

### ISSUE THREAD

**Issue by Tiger-Cyber529** [WH1T3-E4GL3/brute-eagle#1]

**Comment by varunofficia** [comment]
What is the password??

**Comment by mahesh00234h** [comment]
What is password of tool

**Comment by WH1T3-E4GL3** [comment]
It is a paid tool you need to pay me for getting the tool password

**Comment by Abrar021** [comment]
How to paid you

**Comment by bartolingayao** [comment]
HM?

**Comment by rejections** [comment]
if passwd == 'we':
    time.sleep(5)
    print("\033[92m[✓] login sucessfull")
    time.sleep(0.4)
    print("Loading....")
    os.system("clear")
    print('\n')

Next obfuscate your code

**Comment by MR-S74RK** [comment]
AlRedy this is the code vroh

**Comment by MR-S74RK** [comment]
> if passwd == 'we': time.sleep(5) print("\033[92m[✓] login sucessfull") time.sleep(0.4) print("Loading....") os.system("clear") print('\n')
> 
> Next obfuscate your code

We just not completed the project more is coming

**Comment by CPScript** [comment]
password is "we", look in the code

**Comment by shoaib-jamal** [comment]
@WH1T3-E4GL3 Maybe you should have done some obfuscation in your code
